version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  nats:
    image: nats
    container_name: nats_msg
    ports:
      - "4222:4222"
      - "8222:8222"

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"

networks:
  auth_network:
    driver: bridge
