version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - cache_network

  nats:
    image: nats
    container_name: nats_msg
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - cache_network

  grpc-server:
    build:
      context: .
      dockerfile: ./internal/grpc-server/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - cache_network

  gateway-envoy:
    build:
      context: ./config
      dockerfile: Dockerfile
    ports:
      - "8083:8080"

    networks:
      - cache_network

networks:
  cache_network:
    driver: bridge
